- name: Hello World Sample
  hosts: all
  tasks:
    - name: Print some debug information 
      vars: 
        msg: |
          Extra Variables ("vars"):
          {{ vars }}
    
      debug: 
        msg: "{{ msg.split('\n') }}"       
      tags: debug_info
      

