---
apiVersion: tower.ansible.com/v1alpha1
kind: AnsibleJob
metadata:
  name: hello-world
  namespace: bookimport
  labels:
    app.kubernetes.io/name: book-import-prehook
spec:
  tower_auth_secret: aapaccess-bookimport
  job_template_name: book-import-helloworld
  extra_vars:
    app_name: bookimport
    change_request:
      severity: 2
      priority: 2
      implementation_plan: "Updated by Red Hat Advanced Cluster Management for Kubernetes"
      justification: "A new revision was available from the application channel in GitHub."
      description: "The following resources have been updated: [...]"
      risk_impact_analysis: "Changes are made automatically based on approved changes in GitHub."
      test_plan: "Run synthetic validation tests post-deployment."
